### ISSUE TITLE
Concerning Function create_acitivity()

### ISSUE THREAD

**Issue by aliwo** [CureLatte/sparta_save_me_gallery#12]
https://github.com/CureLatte/sparta_save_me_gallery/blob/8dc4eb838037d9654a5048ba7e8aa1dc30efbb4b/activityapp/services/activity_service.py#L14-L19

**Comment by aliwo** [comment]
안녕하세요 ㅎㅎ

우선 에러메세지 부분 부터~
```py
     if model_name == '' or name == '' or pwd == '' or img == '': 
         return 'fail' 
```
을 보면 에러메세지 "fail" 만 보고서는 model_name 이 빈 문자열인지, pwd 가 빈 문자열인지 혹은 모두 다 빈 문자열인지 알 수가 없습니다~
에러 메세지만 보고도 어디가 비었는지 알 수 있다면 더 좋지 않을까요?

**Comment by KEEMSY** [comment]
아하,  저는 작성해야 하는 항목이 4개 뿐이라 어느 부분이 빈 항목인지에 대한 인식은 에러메세지면 확인이 가능할 것이라 생각했는데, 어느부분이 빈칸인지 구체적으로 확인하는 것이 더 좋은 방법일까요?

**Comment by aliwo** [comment]
더 친절한 방법입니다~ 다음 예제 한 번 참고해 보시겠어요?

```py

from django import forms
class ImageSaveForm(forms.Form):
    model_name = forms.CharField(required=True)
    name = forms.CharField(required=True)
    password = forms.CharField(required=True)
    made_image = forms.CharField(required=True)


# 이미지를 저장
@csrf_exempt
def save_made_img(request):
    form = ImageSaveForm(request.POST)  # noqa
    if form.errors:
        return JsonResponse(form.errors.get_json_data())

    if 'success' == create_activity(
        request.POST.get("model_name"),
        request.POST.get("name"),
        request.POST.get("password"),
        request.POST.get("made_image")
    ):
        return JsonResponse({"msg": "Your own masterpiece is successfully saved!"})
    else:
        return JsonResponse({'msg': 'Please check the blank'})


```

**Comment by aliwo** [comment]
https://github.com/CureLatte/sparta_save_me_gallery/blob/eac010f86f182d81d7161b23d6dbcaed3b25ded0/activityapp/tests/test_activity_service.py#L29-L32

테스트 코드를 보면 test_activity 는 문자열을 반환하는데, 변수 이름은 user 입니다 ㅎㅎ
또한 user 는 사용되지 않고 있습니다~
원친적으로 사용되지 않는 변수는 할당하지 않는 것이 좋구용

또, 문자열을 반환하는데 변수명이 user 인 것도 적절하지 않습니다 (혹시 이렇게 지으신 제가 알지 못하는 이유가 있을까요...?)
(놀람 최소화 원칙: https://ko.wikipedia.org/wiki/%EB%86%80%EB%9E%8C_%EC%B5%9C%EC%86%8C%ED%99%94_%EC%9B%90%EC%B9%99)

또, create_activity 의 인자로 int 를 전달하고 있는데, create_activity 는 str 을 받는 함수입니당
`def create_activity(model_name: str, name: str, pwd: int, img: str) -> str:`

**Comment by KEEMSY** [comment]
아하.. 테스트를 할 때에도, 그렇군요..! test_create_Activity는 "같은 name으로 작성된 activity가 있으면 어떤 것을 가져올까?"  하는 호기심에 해본 테스트 였습니다! 그래서 입력값도 편하게 숫자로..... 했었는데 이 부분은 앞으로 주의해보도록하겠습니다!(연습을 실전처럼.....)

변수명을 user로 한 것은 user1이 한 사람이라 생각해서 "user1(어떤 누군가)가 create_activity를 했다!"라고 생각하여 변수명을 작성해보았었습니다. 이 부분도 앞으로 조심하겠습니다!(연습을 실전처럼2.....)

**Comment by aliwo** [comment]
ㅎㅎ 그렇군요~ 스스로 궁금한 내용을 연습해보고 검증해 보시는 건 너무 좋아요!
그런데 연습한 내용은 master 커밋에 들어가지 않아야 한다 라는 것만 기억해주시면 될 것 같습니당

연습 내용을 혹시 팀원들과 공유하기 원하신다면 github issue, gist(https://gist.github.com/) 등등도 방법이에요~

**Comment by aliwo** [comment]
user 가 activity 를 생성한다는 것을 표현하기 원하셨군요~
그렇다면 ...
1. Activity model 과 user 와 relation 을 맺도록 변경
2. create_activity 함수가 user 를 입력 받아서 Activity 를 생성할 때 전달
3. create_activity 함수를 호출할 때 user 전달

이렇게 하면 서로 다른 user 가 activity 를 생성하는 코드가 만들어질 것 같아요 :)
