### ISSUE TITLE
import os, environ?

### ISSUE THREAD

**Issue by aliwo** [CureLatte/sparta_save_me_gallery#13]
https://github.com/CureLatte/sparta_save_me_gallery/blob/8dc4eb838037d9654a5048ba7e8aa1dc30efbb4b/project/settings.py#L17

ModuleNotFoundError: No module named 'environ'

에러가 납니당

**Comment by KEEMSY** [comment]
터미널에 python -m pip install django-environ 후에 import를 해야하는데, 이 부분은 requirments.txt 에 반영을 못했네요..! 바로 수정해보도록하겠습니다 !

**Comment by aliwo** [comment]
호호.. 설치하면 
`AttributeError: '_Environ' object has no attribute 'Env'`
가 터지네용

**Comment by KEEMSY** [comment]
아마도 .env파일이 없어서 발생하는 문제인것같아요...! 슬랙dm으로 .env파일 확인부탁드립니다..!

**Comment by aliwo** [comment]
ㅎㅎ 감사합니다~ 프로젝트 세팅 방법은 README.md 파일에 적어두는 것이 좋아요~

**Comment by KEEMSY** [comment]
아하! 프로젝트세팅 부분도 README.md에 추가해보도록하겠습니다 ! 감사합니다 ㅎㅎ
