### ISSUE TITLE
TDD 에 관해서

### ISSUE THREAD

**Issue by aliwo** [CureLatte/sparta_save_me_gallery#21]
f30b3ae44d2929143d72526aaf08232f6de56556
에 보니 테스트를 먼저 작성하고 제품 코드(get_activity_page())를 작성한 것 처럼 보이네요! ㅎㅎ
아주 잘하셨습니다 :)

**Comment by KEEMSY** [comment]
강의에서 배운 내용으로 열심히 해봤는데, 너무 뿌듯합니다!!(내려가지않는 입꼬리) 그런데 혹시 테스트 코드를 작성할 때,  "테스트가 돌아갈 정도로 최소한"이라는 것에 대해 아직 궁금한게 있습니다..!

1. 함수 안을 완전히 비우고, 그 속을 채워가는게 맞을까요?
2. 아니면 해당 기능을 생각해봤을 때, "이건 무조건 필요하지" 하는 코드는 작성하고 테스트 코드를 작성하는게 맞을까요?

제 생각은 1번인데, 함수안을 완전히 비우고 테스트 코드를 작성하다보면, 결국엔 2번하고 거의 동일하게 가는것같아 질문드립니다..!

**Comment by aliwo** [comment]
오 좋은 질문입니다!
전 1번은 원칙이고
경험이 쌓이면서 2번도 하게 되는게 자연스러운 거라고 생각해요 :)
(저의 생각입니당)
